# Generate production build.
FROM node:latest AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Setup the server.
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/certs /etc/nginx/certs
COPY docker/configs/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
